name: saab_wis
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0-178.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  wis_base:
    path: packages/wis_base
  wis_navigation:
    path: packages/wis_navigation
  neumorphic:
    path: packages/neumorphic

  cupertino_icons: ^1.0.8
  vector_graphics: ^1.1.11+1
  flutter_svg: ^2.0.10+1
  widget_zoom: ^0.0.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  gap: ^3.0.1
  auto_route: ^9.2.2
  flutter_hooks: ^0.20.5
  flutter_fancy_tree_view: ^1.6.0
  collection: ^1.18.0
  flutter_markdown: ^0.7.3+2
  flutter_html_reborn: ^3.0.0
  flutter_html_table: ^3.0.0-beta.2
  markdown: 7.2.2
  expandable_page_view: ^1.0.17
  stroke_text: ^0.0.3
  searchable_listview: ^2.15.2
  font_awesome_flutter: ^10.7.0
  flutter_widget_from_html: ^0.15.2
  csslib: ^0.17.3
  shadow_widget: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  vector_graphics_compiler: ^1.1.11+1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/
